apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-staging
resources:
  - ../../base/podinfo
  - namespace.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
